### ISSUE TITLE
Repository name

### ISSUE THREAD

**Issue by mrepol742** [Jiya398/Jiya398#1]
You can make this repository README.md appear on your public profile by renaming this repository name from `.github` to `Jiya398`
> You can do it by going to this repository settings > Repository name > change `.github` to `Jiya398` and then tap rename.
![Sample Image](https://user-images.githubusercontent.com/62317165/167180805-9a366e00-ae1c-470c-ad5b-bae0748ab0e8.png)

**Comment by Jiya398** [comment]
Thank you for noticing @mrepol742
